/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['app.js']) {
  _$jscoverage['app.js'] = [];
  _$jscoverage['app.js'][1] = 0;
  _$jscoverage['app.js'][2] = 0;
  _$jscoverage['app.js'][3] = 0;
  _$jscoverage['app.js'][6] = 0;
  _$jscoverage['app.js'][7] = 0;
  _$jscoverage['app.js'][8] = 0;
  _$jscoverage['app.js'][9] = 0;
  _$jscoverage['app.js'][10] = 0;
  _$jscoverage['app.js'][11] = 0;
  _$jscoverage['app.js'][12] = 0;
  _$jscoverage['app.js'][13] = 0;
  _$jscoverage['app.js'][14] = 0;
  _$jscoverage['app.js'][15] = 0;
  _$jscoverage['app.js'][16] = 0;
  _$jscoverage['app.js'][17] = 0;
  _$jscoverage['app.js'][18] = 0;
  _$jscoverage['app.js'][19] = 0;
  _$jscoverage['app.js'][20] = 0;
  _$jscoverage['app.js'][21] = 0;
  _$jscoverage['app.js'][22] = 0;
  _$jscoverage['app.js'][23] = 0;
  _$jscoverage['app.js'][24] = 0;
  _$jscoverage['app.js'][26] = 0;
  _$jscoverage['app.js'][29] = 0;
  _$jscoverage['app.js'][30] = 0;
  _$jscoverage['app.js'][31] = 0;
}
_$jscoverage['app.js'][1]++;
(function () {
  _$jscoverage['app.js'][2]++;
  var console;
  _$jscoverage['app.js'][3]++;
  console = console || {log: (function () {
})};
  _$jscoverage['app.js'][6]++;
  google.setOnLoadCallback((function () {
  _$jscoverage['app.js'][7]++;
  var googleEventLoader, loading, login, myService, notification, scope;
  _$jscoverage['app.js'][8]++;
  notification = new MKT.Notification();
  _$jscoverage['app.js'][9]++;
  loading = new MKT.Loading();
  _$jscoverage['app.js'][10]++;
  scope = "http://www.google.com/calendar/feeds/";
  _$jscoverage['app.js'][11]++;
  notification.show("Checking Google Calendar access");
  _$jscoverage['app.js'][12]++;
  if (google.accounts.user.checkLogin(scope)) {
    _$jscoverage['app.js'][13]++;
    myService = new google.gdata.calendar.CalendarService("monket-calendar-2");
    _$jscoverage['app.js'][14]++;
    googleEventLoader = new MKT.GoogleEventLoader(myService, loading);
    _$jscoverage['app.js'][15]++;
    return googleEventLoader.init((function () {
  _$jscoverage['app.js'][16]++;
  var calendar, colourMap, config, dayHighlighter, eventCreator, eventLayoutManager, weekCreator;
  _$jscoverage['app.js'][17]++;
  colourMap = MKT.ColourMap;
  _$jscoverage['app.js'][18]++;
  config = new MKT.MonketCalendarConfig();
  _$jscoverage['app.js'][19]++;
  dayHighlighter = new MKT.DayHighlighter(config);
  _$jscoverage['app.js'][20]++;
  eventCreator = new MKT.EventCreator(googleEventLoader, colourMap, config);
  _$jscoverage['app.js'][21]++;
  weekCreator = new MKT.WeekCreator(config, dayHighlighter, googleEventLoader);
  _$jscoverage['app.js'][22]++;
  eventLayoutManager = new MKT.EventLayoutManager(config, eventCreator);
  _$jscoverage['app.js'][23]++;
  calendar = new MKT.Calendar(config, googleEventLoader, notification, eventLayoutManager, weekCreator, dayHighlighter);
  _$jscoverage['app.js'][24]++;
  return calendar;
}), (function () {
  _$jscoverage['app.js'][26]++;
  return notification.show("Unable to load Google Calendars");
}));
  }
  else {
    _$jscoverage['app.js'][29]++;
    notification.hide();
    _$jscoverage['app.js'][30]++;
    login = new MKT.Login(google.accounts.user, scope);
    _$jscoverage['app.js'][31]++;
    return login.show();
  }
}));
})();
_$jscoverage['app.js'].source = ["(function(){","  var console;","  console = console || {","    log: function() {    }","  };","  google.setOnLoadCallback(function() {","    var googleEventLoader, loading, login, myService, notification, scope;","    notification = new MKT.Notification();","    loading = new MKT.Loading();","    scope = \"http://www.google.com/calendar/feeds/\";","    notification.show(\"Checking Google Calendar access\");","    if (google.accounts.user.checkLogin(scope)) {","      myService = new google.gdata.calendar.CalendarService(\"monket-calendar-2\");","      googleEventLoader = new MKT.GoogleEventLoader(myService, loading);","      return googleEventLoader.init(function() {","        var calendar, colourMap, config, dayHighlighter, eventCreator, eventLayoutManager, weekCreator;","        colourMap = MKT.ColourMap;","        config = new MKT.MonketCalendarConfig();","        dayHighlighter = new MKT.DayHighlighter(config);","        eventCreator = new MKT.EventCreator(googleEventLoader, colourMap, config);","        weekCreator = new MKT.WeekCreator(config, dayHighlighter, googleEventLoader);","        eventLayoutManager = new MKT.EventLayoutManager(config, eventCreator);","        calendar = new MKT.Calendar(config, googleEventLoader, notification, eventLayoutManager, weekCreator, dayHighlighter);","        return calendar;","      }, function() {","        return notification.show(\"Unable to load Google Calendars\");","      });","    } else {","      notification.hide();","      login = new MKT.Login(google.accounts.user, scope);","      return login.show();","    }","  });","})();"];
