/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['colour-map.js']) {
  _$jscoverage['colour-map.js'] = [];
  _$jscoverage['colour-map.js'][1] = 0;
  _$jscoverage['colour-map.js'][2] = 0;
}
_$jscoverage['colour-map.js'][1]++;
(function () {
  _$jscoverage['colour-map.js'][2]++;
  MKT.ColourMap = {"#A32929": "#D96666", "#B1365F": "#E67399", "#7A367A": "#B373B3", "#5229A3": "#8C66D9", "#29527A": "#668CB3", "#2952A3": "#668CD9", "#1B887A": "#59BFB3", "#28754E": "#65AD89", "#0D7813": "#4CB052", "#528800": "#8CBF40", "#88880E": "#BFBF4D", "#AB8B00": "#E0C240", "#BE6D00": "#F2A640", "#B1440E": "#E6804D", "#865A5A": "#BE9494", "#705770": "#A992A9", "#4E5D6C": "#8997A5", "#5A6986": "#94A2BE", "#4A716C": "#85AAA5", "#6E6E41": "#85AAA5", "#8D6F47": "#C4A883"};
})();
_$jscoverage['colour-map.js'].source = ["(function(){","  MKT.ColourMap = {","    '#A32929': '#D96666',","    '#B1365F': '#E67399',","    '#7A367A': '#B373B3',","    '#5229A3': '#8C66D9',","    '#29527A': '#668CB3',","    '#2952A3': '#668CD9',","    '#1B887A': '#59BFB3',","    '#28754E': '#65AD89',","    '#0D7813': '#4CB052',","    '#528800': '#8CBF40',","    '#88880E': '#BFBF4D',","    '#AB8B00': '#E0C240',","    '#BE6D00': '#F2A640',","    '#B1440E': '#E6804D',","    '#865A5A': '#BE9494',","    '#705770': '#A992A9',","    '#4E5D6C': '#8997A5',","    '#5A6986': '#94A2BE',","    '#4A716C': '#85AAA5',","    '#6E6E41': '#85AAA5',","    '#8D6F47': '#C4A883'","  };","})();"];
