/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['loading.js']) {
  _$jscoverage['loading.js'] = [];
  _$jscoverage['loading.js'][1] = 0;
  _$jscoverage['loading.js'][2] = 0;
  _$jscoverage['loading.js'][3] = 0;
  _$jscoverage['loading.js'][4] = 0;
  _$jscoverage['loading.js'][6] = 0;
  _$jscoverage['loading.js'][7] = 0;
}
_$jscoverage['loading.js'][1]++;
(function () {
  _$jscoverage['loading.js'][2]++;
  MKT.Loading = (function () {
});
  _$jscoverage['loading.js'][3]++;
  MKT.Loading.prototype.show = (function (text) {
  _$jscoverage['loading.js'][4]++;
  return $("#loading").fadeIn();
});
  _$jscoverage['loading.js'][6]++;
  MKT.Loading.prototype.hide = (function () {
  _$jscoverage['loading.js'][7]++;
  return $("#loading").fadeOut();
});
})();
_$jscoverage['loading.js'].source = ["(function(){","  MKT.Loading = function() {  };","  MKT.Loading.prototype.show = function(text) {","    return $(\"#loading\").fadeIn();","  };","  MKT.Loading.prototype.hide = function() {","    return $(\"#loading\").fadeOut();","  };","","})();"];
