/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['login.js']) {
  _$jscoverage['login.js'] = [];
  _$jscoverage['login.js'][1] = 0;
  _$jscoverage['login.js'][2] = 0;
  _$jscoverage['login.js'][3] = 0;
  _$jscoverage['login.js'][4] = 0;
  _$jscoverage['login.js'][6] = 0;
  _$jscoverage['login.js'][8] = 0;
  _$jscoverage['login.js'][9] = 0;
  _$jscoverage['login.js'][10] = 0;
  _$jscoverage['login.js'][11] = 0;
}
_$jscoverage['login.js'][1]++;
(function () {
  _$jscoverage['login.js'][2]++;
  MKT.Login = (function (user, scope) {
  _$jscoverage['login.js'][3]++;
  $("#login-button").click((function () {
  _$jscoverage['login.js'][4]++;
  return user.login(scope);
}));
  _$jscoverage['login.js'][6]++;
  return this;
});
  _$jscoverage['login.js'][8]++;
  MKT.Login.prototype.show = (function () {
  _$jscoverage['login.js'][9]++;
  $("#login").removeClass("hidden");
  _$jscoverage['login.js'][10]++;
  $("#login").css("margin-left", parseInt($("#login").width() / -2) + "px");
  _$jscoverage['login.js'][11]++;
  return $("#login").css("margin-top", parseInt($("#login").height() / -2) + "px");
});
})();
_$jscoverage['login.js'].source = ["(function(){","  MKT.Login = function(user, scope) {","    $('#login-button').click(function() {","      return user.login(scope);","    });","    return this;","  };","  MKT.Login.prototype.show = function() {","    $(\"#login\").removeClass(\"hidden\");","    $(\"#login\").css(\"margin-left\", parseInt($(\"#login\").width() / -2) + \"px\");","    return $(\"#login\").css(\"margin-top\", parseInt($(\"#login\").height() / -2) + \"px\");","  };","","})();"];
