/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['namespace.js']) {
  _$jscoverage['namespace.js'] = [];
  _$jscoverage['namespace.js'][1] = 0;
  _$jscoverage['namespace.js'][2] = 0;
}
_$jscoverage['namespace.js'][1]++;
(function () {
  _$jscoverage['namespace.js'][2]++;
  this.MKT = this.MKT || {};
})();
_$jscoverage['namespace.js'].source = ["(function(){","  this.MKT = this.MKT || {};","})();"];
