/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['notification.js']) {
  _$jscoverage['notification.js'] = [];
  _$jscoverage['notification.js'][1] = 0;
  _$jscoverage['notification.js'][2] = 0;
  _$jscoverage['notification.js'][3] = 0;
  _$jscoverage['notification.js'][4] = 0;
  _$jscoverage['notification.js'][5] = 0;
  _$jscoverage['notification.js'][6] = 0;
  _$jscoverage['notification.js'][7] = 0;
  _$jscoverage['notification.js'][9] = 0;
  _$jscoverage['notification.js'][10] = 0;
}
_$jscoverage['notification.js'][1]++;
(function () {
  _$jscoverage['notification.js'][2]++;
  MKT.Notification = (function () {
});
  _$jscoverage['notification.js'][3]++;
  MKT.Notification.prototype.show = (function (text) {
  _$jscoverage['notification.js'][4]++;
  $("#notification-text").html(text);
  _$jscoverage['notification.js'][5]++;
  $("#notification").css("margin-left", parseInt($("#notification").width() / -2) + "px");
  _$jscoverage['notification.js'][6]++;
  $("#notification").css("margin-top", parseInt($("#notification").height() / -2) + "px");
  _$jscoverage['notification.js'][7]++;
  return $("#notification").fadeIn();
});
  _$jscoverage['notification.js'][9]++;
  MKT.Notification.prototype.hide = (function () {
  _$jscoverage['notification.js'][10]++;
  return $("#notification").fadeOut();
});
})();
_$jscoverage['notification.js'].source = ["(function(){","  MKT.Notification = function() {  };","  MKT.Notification.prototype.show = function(text) {","    $(\"#notification-text\").html(text);","    $(\"#notification\").css(\"margin-left\", parseInt($(\"#notification\").width() / -2) + \"px\");","    $(\"#notification\").css(\"margin-top\", parseInt($(\"#notification\").height() / -2) + \"px\");","    return $(\"#notification\").fadeIn();","  };","  MKT.Notification.prototype.hide = function() {","    return $(\"#notification\").fadeOut();","  };","","})();"];
